[project]
name = "repl-nix-scrappingolx"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "discord-py>=2.4.0",
    "selenium>=4.26.1",
    "webdriver-manager>=4.0.2",
]
